# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


minecraft_version = 1.21.1
minecraft_version_range=[1.21.1]
neo_version = 21.1.234
parchment_mappings_version = 2024.11.17
parchment_minecraft_version = 1.21.1
loader_version_range=[1,)
neo_version_range=[21.1.234,)



## Mod Properties


mod_id=tfcscraping
mod_name=TFC Scraping Knives
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=MIT
mod_version=2.0.0
mod_group_id=com.redstoneguy10ls.tfcscraping
mod_authors=redstoneguy10ls
mod_description=A mod that adds new scarping knifes to tfc
mod_credits= thank you to dodo for the textures
